### ISSUE TITLE
no promotion

### ISSUE THREAD

**Issue by iaraiapc** [JuliaPy/SymPy.jl#220]
I have a doubt:

```
using SymPy
@syms t l g pi

solve(2*pi*sqrt(l/g) - t, g)
```
no promotion exists for Float64 and SymPy.Sym

Stacktrace:
 [1] promote_type(::Type{Float64}, ::Type{SymPy.Sym}) at ./promotion.jl:161
 [2] promote at ./promotion.jl:175 [inlined]
 [3] * at ./promotion.jl:250 [inlined]
 [4] *(::Int64, ::Irrational{:π}, ::SymPy.Sym) at ./operators.jl:424

How to solve ?

**Comment by jverzani** [comment]
I can't reproduce this:

```
julia> using SymPy

julia> @syms t l g pi

       solve(2*pi*sqrt(l/g) - t, g)
1-element Array{SymPy.Sym,1}:
 4*l*pi^2/t^2
```

Can you try again with a fresh session and see?

**Comment by iaraiapc** [comment]
```
using SymPy
@syms t l g

solve(2.01*pi*sqrt(l/g) - t, g)
```
using floating number, the error occurs.

**Comment by mzaffalon** [comment]
What is the output of `Pkg.status("SymPy")`?

By the way, on SymPy 0.6.0, I get
```
solve(2*pi*sqrt(l/g) - t, g)
1-element Array{SymPy.Sym,1}:
 39.4784176043575*l/t^2
```
with a floating point number, not the symbolic value.

**Comment by jverzani** [comment]
Yes, I'm guessing this is an older version of SymPy, so please do confirm. As @mzaffalon points out, this works with floating point (which due to 2*pi happening before `pi` is converted to `PI`, SymPy's symbolic "pi").

**Comment by iaraiapc** [comment]
my version: 
- SymPy                         0.6.0

**Comment by iaraiapc** [comment]
The terminal works. With jupyter it does not work.

**Comment by jverzani** [comment]
That is odd. They both use PyCall but I can't see why this wouldn't work. Can you take a screen shot and post of the commands and the error message for a new notebook?

**Comment by mzaffalon** [comment]
@iaraiapc Why are you defining `pi` as symbol in your definition `@syms t l g pi`.

**Comment by iaraiapc** [comment]
hum .... now it worked. I uninstalled sympy and installed again.

**Comment by jverzani** [comment]
Glad to hear this works now. I'm closing the issue now, but please do reopen if this appears again.

**Comment by iaraiapc** [comment]
ok, thanks, @jverzani :)

**Comment by Kelvyn88** [comment]
The problem is still on jupyter after re install SymPy or checkout to the master. Same version 0.6.0

**Comment by jverzani** [comment]
Hmm, What kernel is being used? Hopefully I can replicate on JuliaBox

**Comment by Kelvyn88** [comment]
I fixed! I did a checkout and boot jupyter again. Thanks and sorry.

Kelvyn

**Comment by jverzani** [comment]
Thanks for letting me know. This is an odd issue and it would be nice to identify its cause.

**Comment by Kelvyn88** [comment]
I found the problem. You can replicate this sissue by importing Plots after importing SymPy. If I import SymPY at the end, everything works!! 

Thanks!!!

Kelvyn

**Comment by jverzani** [comment]
Thanks for sharing. I still can't replicate the issue on my Mac. What OS are you using?

**Comment by Kelvyn88** [comment]
Hi, I'm in windows but meter I will try in macOS and Ubuntu. I'll let you know the results.
